BASE_URL = "https://shopiland.ru/"
TEST_URL = "https://www.qa-practice.com/elements/button/simple"
XPATH_CLASS = "//p[@class='css-99ww93']"
XPATH_TEXT = ""
XPATH_DOWNLOAD_NEXT = "//button[contains(text(),'Загрузить еще')]"
